modLoader="javafml"
loaderVersion="[1,)"
license="BSD-2-Clause"
[[mods]]
modId="postgresql_driver"
version="${version}"
displayName="PostgreSQL JDBC Driver"
description='''PostgreSQL JDBC Driver'''
logoFile="postgreslogo.svg"